EXPORT_FUNC(get_version)
EXPORT_FUNC(getc)
EXPORT_FUNC(tstc)
EXPORT_FUNC(putc)
EXPORT_FUNC(puts)
EXPORT_FUNC(printf)
EXPORT_FUNC(malloc)
EXPORT_FUNC(free)
EXPORT_FUNC(udelay)
EXPORT_FUNC(get_timer)
EXPORT_FUNC(vprintf)
EXPORT_FUNC(do_reset)

#ifdef _SC_BUILD_
EXPORT_FUNC(memcmp)
EXPORT_FUNC(memcpy)
EXPORT_FUNC(memset)
EXPORT_FUNC(strlen)
EXPORT_FUNC(get_nand_info)
EXPORT_FUNC(ranand_erase)
EXPORT_FUNC(ranand_write)
EXPORT_FUNC(ranand_read)
EXPORT_FUNC(mtk_nand_read_oob_raw)
EXPORT_FUNC(mtk_nand_read_oob)
EXPORT_FUNC(mtk_nand_erase)
EXPORT_FUNC(mtk_nand_write_oob_raw)
EXPORT_FUNC(mtk_nand_write_oob)
EXPORT_FUNC(vsprintf)
EXPORT_FUNC(sc_rt2880_eth_recv)


EXPORT_FUNC(eth_halt)
EXPORT_FUNC(eth_get_dev)
EXPORT_FUNC(sc_NetLoop)
EXPORT_FUNC(eth_send)
EXPORT_FUNC(init_rx_buf)
EXPORT_FUNC(simple_strtoul)
EXPORT_FUNC(mii_mgr_read)
EXPORT_FUNC(mii_mgr_write)
EXPORT_FUNC(do_sc_regs)
EXPORT_FUNC(do_sc_ramtest)
EXPORT_FUNC(sc_bootcmd_env_update)
#endif
