SC_BUILD=y
SC_STANDALONE=y
SC_UPGRADE=y
SC_CMDSET=y
SC_FLMAP=y
SC_GPIO=y
SC_NMRP=y
SC_TFTP_REC=y
SC_MII=y
SC_RAMTEST=y
SC_WATCHDOG=n
SC_DEBUG=y
SC_NAND_SUPPORT=y
SC_VERIFY_ECC=y
SC_FINAL_BOOT=n
SC_SPI_SUPPORT=n
SC_DUAL_IMAGE=n
SC_AMT=n
SC_CHECKSUM=n
SC_HWTEST=n
SC_DEV_BUILD=n
SC_HTTP=n

export SC_BUILD
export SC_STANDALONE
export SC_UPGRADE
export SC_CMDSET
export SC_FLMAP
export SC_GPIO
export SC_NMRP
export SC_TFTP_REC
export SC_MII
export SC_RAMTEST
export SC_WATCHDOG
export SC_DEBUG
export SC_NAND_SUPPORT
export SC_VERIFY_ECC
export SC_FINAL_BOOT
export SC_SPI_SUPPORT
export SC_DUAL_IMAGE
export SC_AMT
export SC_CHECKSUM
export SC_HWTEST
export SC_DEV_BUILD
export SC_HTTP
